#!/bin/sh

# xonsh init
pip install xonsh-apt-tabcomplete xonsh-autoxsh xontrib-avox xonsh-docker-tabcomplete xontrib-fzf-widgets xontrib-hist-navigator xontrib-histcpy xontrib-output-search xontrib-pipeliner xontrib-prompt-bar xontrib-pyenv xontrib-readable-traceback xontrib-ssh-agent xontrib-z


